name: Update Languages in README

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia-noite (UTC)
  workflow_dispatch:     # Permite execução manual também

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
        run: python update_readme.py  # Substitua pelo nome real do seu script Python

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: update languages section in README" || echo "No changes to commit"
          git push
